version: '3.8'

services:
  db:
    build: ./db
    volumes:
      - db-data:/db

  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - db-data:/db
    depends_on:
      - db

volumes:
  db-data:
